config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :faphras
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'faphras#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/faphra.rb
class Faphra < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :faphras
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/faphras_controller.rb
class FaphrasController < ApplicationController
  before_action :set_faphra, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /faphras
  # GET /faphras.json
  def index
    @faphras = Faphra.all.order("created_at DESC")
    @faphra = Faphra.new
    @users = User.all 
  end

  # GET /faphras/1
  # GET /faphras/1.json
  def show
  end

  # GET /faphras/new
  def new
    @faphra = current_user.faphras.build
  end

  # GET /faphras/1/edit
  def edit
  end

  # POST /faphras
  # POST /faphras.json
  def create
    @faphra = current_user.faphras.build(faphra_params)

    respond_to do |format|
      if @faphra.save
        format.html { redirect_to root_path, notice: 'Faphra was successfully created.' }
        format.json { render :show, status: :created, location: @faphra }
      else
        format.html { render :new }
        format.json { render json: @faphra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faphras/1
  # PATCH/PUT /faphras/1.json
  def update
    respond_to do |format|
      if @faphra.update(faphra_params)
        format.html { redirect_to @faphra, notice: 'Faphra was successfully updated.' }
        format.json { render :show, status: :ok, location: @faphra }
      else
        format.html { render :edit }
        format.json { render json: @faphra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faphras/1
  # DELETE /faphras/1.json
  def destroy
    @faphra.destroy
    respond_to do |format|
      format.html { redirect_to faphras_url, notice: 'Faphra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faphra
      @faphra = Faphra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def faphra_params
      params.require(:faphra).permit(:body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController 

	private

	def sign_up_params 
		params.require(:user).permit(:name, :username, :email, :password, 
			:password_confirmation)
	end

	def account_update_params 
		params.require(:user).permit(:name, :username, :email, :password, 
			:password_confirmation, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faphras_helper.rb
module FaphrasHelper
end

app/views/faphras/_feed.html.erb
<div class="column if-half">
	<% if user_signed_in? %>
	  <article class="media box">
		<figure class="media-left">
			<p class="image is-64x64">
				<%= gravatar_image_tag(current_user.email, 
					   size: 64, alt: current_user.name) %>
			</p>
		</figure>
		<div class="media-content">
			 <%= render 'faphras/form' %>
		</div>
	  </article>	
	<% end %>

  <% @faphras.each do |faphra| %>
	<div class="box">
		<article class="media">
			<div class="media-left">
				<figure class="image is-64x64">
					<%= gravatar_image_tag(faphra.user.email, 
					   size: 64, alt: faphra.user.name) %>
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<strong><%= faphra.user.name %></strong><br />
					<small><%= faphra.user.username %></small><br />
					<p><%= faphra.body %></p>
				</div>

				<% if user_signed_in? %>
				  <nav class="level">
					<div class="level-left is-mobile">
						<%= link_to faphra, class: "level-item" do %>
							<span class="icon">
								<i class="fa fa-link" aria-hidden="true"></i>
							</span>
						<% end %>
						<%= link_to edit_faphra_path(faphra), class: "level-item" do %>
							<span class="icon">
								<i class="fa fa-pencil" aria-hidden="true"></i>
							</span>
						<% end %>
						<%= link_to faphra, method: :delete, data: { confirm: "Are you sure?" } do %>
							<span class="icon">
								<i class="fa fa-trash-o" aria-hidden="true"></i>
							</span>
						<% end %>
					</div>
				  </nav>
				<% end %>

			</div>
		</article>
	</div>
  <% end %>
</div>

app/views/faphras/_form.html.erb
<%= simple_form_for(@faphra) do |f| %>
  <%= f.error_notification %>

  <div class="field">
    <div class="control">
      <%= f.input :body, label: "Today favorite phrase", 
        input_html: { class: "textarea" }, wrapper: false, 
        label_html: { class: "label" },
        placeholder: "Add your new favorite phrase...", autofocus: true %>
    </div>
  </div>

  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/faphras/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, 
						  size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="content">
					<p>
						<strong><%= current_user.name %></strong><br />
						<small><%= current_user.username %></small>
					</p>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Faphras</p>
						<p class="title is-6"><%= current_user.faphras.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">34</p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">56</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/faphras/_trends.html.erb
<dir class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
	</nav>
</dir>

app/views/faphras/_who_to_follow.html.erb
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>
    <% @users.each do |user| %>
      <% if user != current_user %>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-32x32">
						 <%= gravatar_image_tag(user.email, 
							  size: 64, alt: user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= user.name %></strong>
							<small><%= user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
	  <% end %>	
	<% end %>
	</nav>
</div>

app/views/faphras/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Faphra</h1>
				<%= render 'form', faphra: @faphra %>
			</div>
		</div>
	</div>
</div>

<div class="navbar is-fixed-botton">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to "Cancel", faphras_path, class: "button is-dark" %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/faphras/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>	
        <%= render 'feed' %>
        <%= render 'who_to_follow' %>
      <% else %>
        <%= render 'feed' %>
        <%= render 'trends' %>
      <% end %>
    </div>
  </div>
</section>

app/views/faphras/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Faphra</h1>
				<%= render 'form', faphra: @faphra %>
			</div>
		</div>
	</div>
</div>

<div class="navbar is-fixed-botton">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to "Cancel", faphras_path, class: "button is-dark" %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/faphras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @faphra.body %>
</p>

<%= link_to 'Edit', edit_faphra_path(@faphra) %> |
<%= link_to 'Back', faphras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saywhat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-primary global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "nav-item" do %>
          <h1 class="title is-5">Saywhat</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'New Faphra', root_path, class: "button is-info is-inverted" %>
              </p>

            <% if user_signed_in? %>
              <p class="control">
                <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
              </p>
              <p>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-info" %>
              </p>
            <% else %>
            <p class="control">
              <%= link_to 'Sign In', user_session_path, class: "button is-info" %>
            </p>
            <p class="control">
              <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
            </p>
            <% end %>

            </div>
            </div>
          </div>
        </div>

      </nav>
    </nav>



    <%= yield %>
  </body>
</html>